[features]
seeds = false
skip-lint = false
[programs.localnet]
mysolanaapp = "HnNNM8vWVVPpn4hQt1jQTddEWZrbVkyVwEuVPKprnQoj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/komalkrishna/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
